# Generated by Django 4.1.3 on 2024-06-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreaction',
            old_name='uid',
            new_name='user',
        ),
    ]
