# Generated by Django 4.1.3 on 2024-06-16 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_remove_postreaction_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rareapi.post'),
        ),
    ]
