# Generated by Django 4.1.3 on 2024-06-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_alter_post_rare_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='', max_length=500),
        ),
    ]
