# Generated by Django 4.1.3 on 2024-06-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0005_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
